//go:build !windows

package menu

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ViSiON-3/vision-3-bbs/internal/config"
)

func TestDoorcovDosDropfileName(t *testing.T) {
	for in, want := range map[string]string{
		"DOOR32.SYS": "DOOR32.SYS", " door32.sys ": "DOOR32.SYS", "chain.txt": "CHAIN.TXT",
		"DorInfo1.Def": "DORINFO1.DEF", "DOOR.SYS": "DOOR.SYS", "": "DOOR.SYS", "NONE": "DOOR.SYS",
	} {
		if got := dosDropfileName(in); got != want {
			t.Errorf("dosDropfileName(%q) = %q, want %q", in, got, want)
		}
	}
}

// doorcovBatch writes EXTERNAL.BAT for cfg on node 3 and returns its lines.
func doorcovBatch(t *testing.T, cfg config.DoorConfig) []string {
	t.Helper()
	ctx := &DoorCtx{
		Config:     cfg,
		NodeNumStr: "3",
		Subs:       map[string]string{"{DOSDROPFILE}": `C:\NODES\TEMP3\DOOR.SYS`, "{USERHANDLE}": "Neo"},
	}
	path := filepath.Join(t.TempDir(), "EXTERNAL.BAT")
	if err := writeBatchFile(ctx, path); err != nil {
		t.Fatalf("writeBatchFile: %v", err)
	}
	if fi, err := os.Stat(path); err != nil || fi.Mode().Perm() != 0o600 {
		t.Errorf("batch file mode %v, err %v; want 0600", fi.Mode().Perm(), err)
	}
	return doorcovLines(t, path)
}

func TestDoorcovWriteBatchFile(t *testing.T) {
	for _, tc := range []struct {
		name string
		cfg  config.DoorConfig
		want []string
	}{
		{
			"bare command",
			config.DoorConfig{Commands: []string{"LORD.EXE /N{NODE} /D{DOSDROPFILE} {USERHANDLE}"}},
			[]string{"@echo off", `SET PATH=%PATH%;D:\dosemu`, "c:", "cls",
				`LORD.EXE /N3 /DC:\NODES\TEMP3\DOOR.SYS Neo`, "exitemu"},
		},
		{
			// The FOSSIL driver loads before the screen clear that marks the
			// end of boot, and the door's drive is selected before its cd.
			"fossil driver and working directory",
			config.DoorConfig{
				FossilDriver:     `C:\UTILS\X00.EXE eliminate`,
				WorkingDirectory: `D:\DOORS\LORD GAME`,
				Commands:         []string{"START.EXE"},
			},
			[]string{"@echo off", `SET PATH=%PATH%;D:\dosemu`, "c:", `C:\UTILS\X00.EXE eliminate`, "cls",
				"D:", `cd "D:\DOORS\LORD GAME"`, "START.EXE", "exitemu"},
		},
		{
			"working directory without a drive",
			config.DoorConfig{WorkingDirectory: `\DOORS`, Commands: nil},
			[]string{"@echo off", `SET PATH=%PATH%;D:\dosemu`, "c:", "cls", `cd "\DOORS"`, "exitemu"},
		},
		{
			// A batch file run without CALL never returns, so exitemu would
			// not run; only a line whose program is a .BAT gets one.
			"batch files are called",
			config.DoorConfig{Commands: []string{
				"start.bat {NODE}", "CALL SETUP.BAT", "  call other.bat", "EDIT.EXE NOTES.BAT", "",
			}},
			[]string{"@echo off", `SET PATH=%PATH%;D:\dosemu`, "c:", "cls",
				"CALL start.bat 3", "CALL SETUP.BAT", "  call other.bat", "EDIT.EXE NOTES.BAT", "", "exitemu"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := doorcovBatch(t, tc.cfg)
			if strings.Join(got, "\n") != strings.Join(tc.want, "\n") {
				t.Errorf("EXTERNAL.BAT =\n%s\nwant\n%s", strings.Join(got, "\n"), strings.Join(tc.want, "\n"))
			}
		})
	}
}

func TestDoorcovWriteBatchFileError(t *testing.T) {
	ctx := &DoorCtx{NodeNumStr: "3"}
	if err := writeBatchFile(ctx, filepath.Join(t.TempDir(), "missing", "EXTERNAL.BAT")); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("err = %v, want not-exist", err)
	}
}

// doorcovDosemurc writes a per-node dosemurc for cfg and returns its content.
func doorcovDosemurc(t *testing.T, cfg config.DoorConfig) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "dosemurc")
	ctx := &DoorCtx{Config: cfg, NodeNumber: 3}
	if err := writeDosemurc(ctx, path, "/bbs/drive_c", "/bbs/drive_c/nodes/temp3"); err != nil {
		t.Fatalf("writeDosemurc: %v", err)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// The sysop's own dosemurc is the base, minus the settings the BBS has to
// control; which of those it then sets depends on FOSSIL versus terminal mode.
func TestDoorcovWriteDosemurc(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	base := filepath.Join(t.TempDir(), "custom.rc")
	custom := "$_cpu = \"80486\"\n  $_com1 = \"/dev/ttyS0\"\n$_hdimage = \"+0\"\n$_video = \"vga\"\n$_vga = (on)\n$_xms = (8192)\n"
	if err := os.WriteFile(base, []byte(custom), 0o644); err != nil {
		t.Fatal(err)
	}

	t.Run("terminal mode", func(t *testing.T) {
		got := doorcovDosemurc(t, config.DoorConfig{DosemuConfig: base})
		want := "$_cpu = \"80486\"\n$_xms = (8192)\n\n" +
			"\n# Generated by ViSiON/3 for node 3\n" +
			"$_lredir_paths = \"/bbs/drive_c/nodes/temp3\"\n" +
			"$_term_color = (on)\n$_term_esc_char = (27)\n"
		if got != want {
			t.Errorf("dosemurc =\n%q\nwant\n%q", got, want)
		}
	})

	t.Run("fossil mode", func(t *testing.T) {
		got := doorcovDosemurc(t, config.DoorConfig{DosemuConfig: base, FossilDriver: "X00.EXE"})
		want := "$_cpu = \"80486\"\n$_xms = (8192)\n\n" +
			"\n# Generated by ViSiON/3 for node 3\n" +
			"$_lredir_paths = \"/bbs/drive_c/nodes/temp3\"\n" +
			"$_com1 = \"virtual\"\n$_video = \"none\"\n"
		if got != want {
			t.Errorf("dosemurc =\n%q\nwant\n%q", got, want)
		}
	})

	t.Run("no base config", func(t *testing.T) {
		got := doorcovDosemurc(t, config.DoorConfig{})
		want := "\n\n# Generated by ViSiON/3 for node 3\n" +
			"$_lredir_paths = \"/bbs/drive_c/nodes/temp3\"\n" +
			"$_term_color = (on)\n$_term_esc_char = (27)\n"
		if got != want {
			t.Errorf("dosemurc =\n%q\nwant\n%q", got, want)
		}
	})

	// With no door-specific config the BBS user's own ~/.dosemu/.dosemurc is
	// the base.
	t.Run("home dosemurc", func(t *testing.T) {
		home := os.Getenv("HOME")
		if err := os.MkdirAll(filepath.Join(home, ".dosemu"), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(home, ".dosemu", ".dosemurc"), []byte("$_layout = \"us\"\n$_com1 = \"x\"\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		got := doorcovDosemurc(t, config.DoorConfig{})
		if !strings.HasPrefix(got, "$_layout = \"us\"\n") || strings.Contains(got, "$_com1") {
			t.Errorf("home dosemurc not used as the filtered base:\n%s", got)
		}
	})

	t.Run("missing base config", func(t *testing.T) {
		ctx := &DoorCtx{Config: config.DoorConfig{DosemuConfig: filepath.Join(t.TempDir(), "nope.rc")}}
		out := filepath.Join(t.TempDir(), "dosemurc")
		err := writeDosemurc(ctx, out, "/c", "/c/nodes/temp0")
		if !errors.Is(err, os.ErrNotExist) || !strings.Contains(err.Error(), "failed to read base dosemurc") {
			t.Errorf("err = %v, want a base config read failure", err)
		}
		if doorcovExists(out) {
			t.Error("dosemurc written despite the unreadable base config")
		}
	})
}

// doorcovFakeDosemu installs body as the BBS's dosemu binary. Before body
// runs, $args holds the command line, $node the per-node directory (the
// directory of the -f config) and $drive the --Fdrive_c argument, so a script
// can show what the BBS prepared for the emulator.
func doorcovFakeDosemu(t *testing.T, env *menuEnv, body string) {
	t.Helper()
	path := doorcovScript(t, `args="$*"
while [ $# -gt 0 ]; do
  case "$1" in
    -f) node=$(dirname "$2") ;;
    --Fdrive_c) drive=$2 ;;
  esac
  shift
done
`+body)
	setServerField(env.e, func(c *config.ServerConfig) { c.DosemuPath = path })
}

// A terminal-mode DOS door: the emulator is started in the drive_c directory
// with the per-node config and batch file, its boot chatter is withheld up to
// the batch file's screen clear, and the caller's keys reach it. The dropfiles
// and batch file exist while it runs and are gone afterwards.
func TestDoorcovDOSDoorTerminalMode(t *testing.T) {
	env := newMenuEnv(t)
	reply := filepath.Join(t.TempDir(), "reply")
	doorcovFakeDosemu(t, env, `
echo "BOOT-CHATTER"
printf '\033[2J'
echo "ARGS:$args"
echo "CWD:$(pwd -P) QUIET:$DOSEMU_QUIET"
echo "FILES:$(ls "$node" | tr '\n' ' ')"
echo "BATCH:$(tr -d '\r' < "$node/EXTERNAL.BAT" | tr '\n' '|')"
echo "RC:$(grep -c '_term_color' "$node/dosemurc")"
printf 'KEY?'
read key
echo "$key" > `+reply)

	driveC := filepath.Join(t.TempDir(), "drive_c")
	s := newDoorcovSession()
	s.whenOutput("KEY?", func() { s.send("go\n") })
	ctx := doorcovCtx(env, s, config.DoorConfig{
		IsDOS:        true,
		DriveCPath:   driveC,
		DropfileType: "door32.sys",
		Commands:     []string{`LORD.EXE /N{NODE} {DOSDROPFILE} {DOSNODEDIR}`},
	})
	t.Setenv("HOME", t.TempDir())

	if err := doorcovExec(t, s, executeDOSDoor, ctx); err != nil {
		t.Fatalf("executeDOSDoor: %v", err)
	}

	nodePath := filepath.Join(driveC, "nodes", "temp3")
	realDriveC, err := filepath.EvalSymlinks(driveC)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(s.output(), "BOOT-CHATTER") {
		t.Errorf("boot text reached the caller:\n%s", s.output())
	}
	if !strings.HasPrefix(s.output(), "\x1b[2J") {
		t.Errorf("output does not start at the screen clear: %q", s.output())
	}
	doorcovHas(t, s,
		"ARGS:-t -f "+filepath.Join(nodePath, "dosemurc")+" --Fdrive_c "+driveC+
			` -E C:\NODES\TEMP3\EXTERNAL.BAT -o `+filepath.Join(nodePath, "dosemu_boot.log"),
		"CWD:"+realDriveC+" QUIET:1",
		"FILES:CHAIN.TXT DOOR.SYS DOOR32.SYS DORINFO1.DEF EXTERNAL.BAT dosemurc ",
		`BATCH:@echo off|SET PATH=%PATH%;D:\dosemu|c:|cls|LORD.EXE /N3 C:\NODES\TEMP3\DOOR32.SYS C:\NODES\TEMP3|exitemu|`,
		"RC:1",
	)
	if got := doorcovReply(t, reply); got != "go\n" {
		t.Errorf("door read %q, want %q", got, "go\n")
	}

	wantSubs := map[string]string{
		"{NODEDIR}": nodePath, "{DROPFILE}": filepath.Join(nodePath, "DOOR32.SYS"),
		"{DOSNODEDIR}": `C:\NODES\TEMP3`, "{DOSDROPFILE}": `C:\NODES\TEMP3\DOOR32.SYS`,
	}
	for k, want := range wantSubs {
		if ctx.Subs[k] != want {
			t.Errorf("Subs[%s] = %q, want %q", k, ctx.Subs[k], want)
		}
	}
	for _, name := range []string{"DOOR.SYS", "DOOR32.SYS", "DORINFO1.DEF", "CHAIN.TXT", "EXTERNAL.BAT"} {
		if doorcovExists(filepath.Join(nodePath, name)) {
			t.Errorf("%s left behind in the node directory", name)
		}
	}
}

// A FOSSIL door talks over the emulated serial port: no -t, the config maps
// COM1 to the PTY, and boot text is withheld up to the door's first escape
// sequence rather than a screen clear.
func TestDoorcovDOSDoorFossilMode(t *testing.T) {
	env := newMenuEnv(t)
	doorcovFakeDosemu(t, env, `
echo "BOOT-CHATTER"
printf '\033[1;32m'
echo "ARGS:$args"
echo "RC:$(grep -c '_com1 = "virtual"' "$node/dosemurc")"
echo "BATCH:$(tr -d '\r' < "$node/EXTERNAL.BAT" | tr '\n' '|')"
printf 'KEY?'
read key
exit 3`)

	// A relative drive_c is resolved against the BBS root, the directory
	// holding configs/.
	s := newDoorcovSession()
	s.whenOutput("KEY?", func() { s.send("\n") })
	ctx := doorcovCtx(env, s, config.DoorConfig{
		IsDOS:          true,
		DriveCPath:     "dos/drive_c",
		FossilDriver:   `C:\X00.EXE`,
		Commands:       []string{"GAME.BAT"},
		CleanupCommand: "touch",
		CleanupArgs:    []string{filepath.Join(env.root, "cleaned-{NODE}")},
	})

	// The emulator's exit status is the door's result; cleanup runs anyway.
	err := doorcovExec(t, s, executeDOSDoor, ctx)
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) || exitErr.ExitCode() != 3 {
		t.Errorf("err = %v, want exit status 3", err)
	}

	driveC := filepath.Join(env.root, "dos", "drive_c")
	if strings.Contains(s.output(), "BOOT-CHATTER") || !strings.HasPrefix(s.output(), "\x1b[1;32m") {
		t.Errorf("output not gated on the first escape: %q", s.output())
	}
	doorcovHas(t, s,
		"ARGS:-f "+filepath.Join(driveC, "nodes", "temp3", "dosemurc")+" --Fdrive_c "+driveC+" -E ",
		"RC:1",
		`BATCH:@echo off|SET PATH=%PATH%;D:\dosemu|c:|C:\X00.EXE|cls|CALL GAME.BAT|exitemu|`,
	)
	if !doorcovExists(filepath.Join(env.root, "cleaned-3")) {
		t.Error("cleanup command did not run after the door failed")
	}
}

// If the marker that ends boot never comes, the gate gives up after 32KB and
// lets everything through, so a door that draws without it is still playable.
func TestDoorcovDOSDoorGateFlushesAfter32KB(t *testing.T) {
	for name, fossil := range map[string]string{"terminal": "", "fossil": "X00.EXE"} {
		t.Run(name, func(t *testing.T) {
			env := newMenuEnv(t)
			doorcovFakeDosemu(t, env, `
head -c 40000 /dev/zero | tr '\0' 'x'
printf 'KEY?'
read key
printf 'MORE?'
read key`)
			t.Setenv("HOME", t.TempDir())

			s := newDoorcovSession()
			s.whenOutput("KEY?", func() { s.send("\n") })
			s.whenOutput("MORE?", func() { s.send("\n") })
			ctx := doorcovCtx(env, s, config.DoorConfig{IsDOS: true, FossilDriver: fossil})

			if err := doorcovExec(t, s, executeDOSDoor, ctx); err != nil {
				t.Fatalf("executeDOSDoor: %v", err)
			}
			if got := strings.Count(s.output(), "x"); got != 40000 {
				t.Errorf("caller received %d of the door's 40000 bytes", got)
			}
			// The default drive_c is the BBS user's ~/.dosemu/drive_c.
			if !doorcovExists(filepath.Join(os.Getenv("HOME"), ".dosemu", "drive_c", "nodes", "temp3", "dosemurc")) {
				t.Error("node directory not created under ~/.dosemu/drive_c")
			}
		})
	}
}

// An emulator that dies during boot never opens the gate: the caller sees
// none of its output.
func TestDoorcovDOSDoorGateNeverOpens(t *testing.T) {
	for name, fossil := range map[string]string{"terminal": "", "fossil": "X00.EXE"} {
		t.Run(name, func(t *testing.T) {
			env := newMenuEnv(t)
			doorcovFakeDosemu(t, env, `echo "dosemu: cannot boot"; exit 1`)
			s := newDoorcovSession()
			ctx := doorcovCtx(env, s, config.DoorConfig{IsDOS: true, DriveCPath: t.TempDir(), FossilDriver: fossil})
			t.Setenv("HOME", t.TempDir())

			err := doorcovExec(t, s, executeDOSDoor, ctx)
			var exitErr *exec.ExitError
			if !errors.As(err, &exitErr) || exitErr.ExitCode() != 1 {
				t.Errorf("err = %v, want exit status 1", err)
			}
			if s.output() != "" {
				t.Errorf("boot output reached the caller: %q", s.output())
			}
		})
	}
}

func TestDoorcovDOSDoorSetupErrors(t *testing.T) {
	env := newMenuEnv(t)
	t.Setenv("HOME", t.TempDir())

	t.Run("emulator not installed", func(t *testing.T) {
		driveC := t.TempDir()
		setServerField(env.e, func(c *config.ServerConfig) { c.DosemuPath = "/nonexistent/dosemu2.bin" })
		s := newDoorcovSession()
		err := doorcovExec(t, s, executeDOSDoor, doorcovCtx(env, s, config.DoorConfig{IsDOS: true, DriveCPath: driveC}))
		if !errors.Is(err, os.ErrNotExist) || !strings.Contains(err.Error(), "failed to start dosemu2 with pty") {
			t.Errorf("err = %v, want a start failure wrapping not-exist", err)
		}
		// Nothing of the caller's is left lying around after the failure.
		if doorcovExists(filepath.Join(driveC, "nodes", "temp3", "DOOR.SYS")) {
			t.Error("dropfiles left behind after the emulator failed to start")
		}
	})

	// With no drive_c configured the default is under the BBS user's home,
	// so not knowing the home directory is fatal.
	t.Run("no home directory for the default drive_c", func(t *testing.T) {
		t.Setenv("HOME", "")
		s := newDoorcovSession()
		err := doorcovExec(t, s, executeDOSDoor, doorcovCtx(env, s, config.DoorConfig{IsDOS: true}))
		if err == nil || !strings.Contains(err.Error(), "failed to get home directory") {
			t.Errorf("err = %v, want a home directory failure", err)
		}
	})

	t.Run("node directory cannot be created", func(t *testing.T) {
		file := filepath.Join(t.TempDir(), "drive_c")
		if err := os.WriteFile(file, nil, 0o644); err != nil {
			t.Fatal(err)
		}
		s := newDoorcovSession()
		err := doorcovExec(t, s, executeDOSDoor, doorcovCtx(env, s, config.DoorConfig{IsDOS: true, DriveCPath: file}))
		if err == nil || !strings.Contains(err.Error(), "failed to create node directory") {
			t.Errorf("err = %v, want a node directory failure", err)
		}
	})

	t.Run("dropfile cannot be written", func(t *testing.T) {
		driveC := t.TempDir()
		if err := os.MkdirAll(filepath.Join(driveC, "nodes", "temp3", "CHAIN.TXT"), 0o755); err != nil {
			t.Fatal(err)
		}
		s := newDoorcovSession()
		err := doorcovExec(t, s, executeDOSDoor, doorcovCtx(env, s, config.DoorConfig{IsDOS: true, DriveCPath: driveC}))
		if err == nil || !strings.Contains(err.Error(), "failed to generate dropfiles: failed to generate CHAIN.TXT") {
			t.Errorf("err = %v, want a dropfile failure", err)
		}
	})

	t.Run("batch file cannot be written", func(t *testing.T) {
		driveC := t.TempDir()
		if err := os.MkdirAll(filepath.Join(driveC, "nodes", "temp3", "EXTERNAL.BAT", "sub"), 0o755); err != nil {
			t.Fatal(err)
		}
		s := newDoorcovSession()
		err := doorcovExec(t, s, executeDOSDoor, doorcovCtx(env, s, config.DoorConfig{IsDOS: true, DriveCPath: driveC}))
		if err == nil || !strings.Contains(err.Error(), "failed to write batch file") {
			t.Errorf("err = %v, want a batch file failure", err)
		}
	})

	t.Run("base dosemurc unreadable", func(t *testing.T) {
		driveC := t.TempDir()
		s := newDoorcovSession()
		err := doorcovExec(t, s, executeDOSDoor, doorcovCtx(env, s, config.DoorConfig{
			IsDOS: true, DriveCPath: driveC, DosemuConfig: filepath.Join(driveC, "missing.rc"),
		}))
		if !errors.Is(err, os.ErrNotExist) || !strings.Contains(err.Error(), "failed to write dosemurc") {
			t.Errorf("err = %v, want a dosemurc failure", err)
		}
	})
}
