package stringformat

// FormattedKeys lists every strings.json key whose value is handed to fmt at
// some call site, and whose directives must therefore match the arguments that
// call site passes.
//
// Most BBS strings are printed verbatim and are not listed here. A few of those
// legitimately contain a percent sign that is not a directive -- badUDRatio ends
// "(|15|RA%|09)", where the % is literal text followed by a pipe colour code --
// so running every string through a format parser would report working strings
// as broken.
//
// Keep this in step with the source: TestFormattedKeysMatchCallSites fails if a
// key here no longer reaches fmt, or if a key that does reach fmt is missing, so
// a newly formatted string cannot be added without also being validated.
var FormattedKeys = []string{
	"addedToBatchFormat",
	"batchClearedFormat",
	"batchCountFormat",
	"cfgColorSelectPrompt",
	"cfgColorSet",
	"cfgFileColumnsToggle",
	"cfgFileListModeSet",
	"cfgSaveError",
	"cfgScreenHeightPrompt",
	"cfgScreenHeightSet",
	"cfgScreenWidthPrompt",
	"cfgScreenWidthSet",
	"cfgStringPrompt",
	"cfgStringPromptCurrent",
	"cfgStringUpdated",
	"cfgTermTypeSet",
	"cfgToggleFormat",
	"cfgViewBarColor",
	"cfgViewCustomPrompt",
	"cfgViewFileListMode",
	"cfgViewHotKeys",
	"cfgViewMorePrompts",
	"cfgViewMsgHeader",
	"cfgViewNote",
	"cfgViewPromptColor",
	"cfgViewRealName",
	"cfgViewScreenHeight",
	"cfgViewScreenWidth",
	"cfgViewTermType",
	"cfgViewText2Color",
	"cfgViewTextColor",
	"chatJoinMsg",
	"chatLeaveMsg",
	"chatPrivateMsgFormat",
	"chatRoomListEntry",
	"chatSystemPrefix",
	"chatTopicMsg",
	"confCurrentAreaFormat",
	"confNotFound",
	"doorAccessDenied",
	"doorDropfileError",
	"doorErrorFormat",
	"doorNotFoundFormat",
	"downloadFinishedFormat",
	"execDoorNotConfigured",
	"execFileLoadError",
	"execIPLockout",
	"execMenuLoadError",
	"execMenuPasswordPrompt",
	"execNewMailCount",
	"execPendingValidation",
	"execReadmailPlaceholder",
	"execRunCommandError",
	"execRunCommandNotFound",
	"execRunDoorError",
	"execStatsError",
	"fileNewscanComplete",
	"fileNewscanConfigSaved",
	"fileNotFoundFormat",
	"filePromptFormat",
	"matrixAccountCannotLogon",
	"matrixAccountValidated",
	"msgNoThreadFound",
	"pageMessageFormat",
	"pageNodeListEntry",
	"pageSent",
	"scanAreaProgress",
	"scanConfigSaved",
	"scanDateLine",
	"scanFromLine",
	"scanRangeEndPrompt",
	"scanRangeLine",
	"scanRangeStartPrompt",
	"scanToLine",
	"scanUpdateLine",
	"scanWhichLine",
	"searchResultsHeader",
	"searchResultsSummary",
	"statsActiveNodes",
	"statsBBSName",
	"statsDate",
	"statsSysOp",
	"statsTime",
	"statsTotalCalls",
	"statsTotalFiles",
	"statsTotalMessages",
	"statsTotalUsers",
	"statsVersion",
	"updatePtrsSuccess",
}
