package ftn

import "testing"

func TestHasPlaceholdersDetectsTemplate(t *testing.T) {
	template := `# binkd.conf template
log /opt/vision3/data/logs/binkd.log
inbound /opt/vision3/data/ftn/secure_in
node 21:1/123@fsxnet hub.example.com PASSWORD
`
	if !HasPlaceholders(template, "/bbs") {
		t.Fatal("raw template must be detected as containing placeholders")
	}
}

func TestHasPlaceholdersCleanConf(t *testing.T) {
	clean := `# binkd.conf - Generated by FTN Setup Wizard
# note: /opt/vision3 in a comment must not count
sysname "My Board"
log /bbs/data/logs/binkd.log
inbound /bbs/data/ftn/secure_in
node 21:4/158@fsxnet agency.bbs.nz:24556 secret
`
	if HasPlaceholders(clean, "/bbs") {
		t.Fatal("wizard-generated conf must not be flagged")
	}
}

func TestHasPlaceholdersIgnoresRealRootMatchingPlaceholder(t *testing.T) {
	// A sysop whose real BBS root IS /opt/vision3 has legitimate paths that
	// contain the placeholder token; those must not be flagged.
	conf := `log /opt/vision3/data/logs/binkd.log
inbound /opt/vision3/data/ftn/secure_in
`
	if HasPlaceholders(conf, "/opt/vision3") {
		t.Fatal("paths under the real BBS root must not be flagged as placeholders")
	}
}
