package ftn

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// BinkdNode holds the parameters for a binkd node line.
type BinkdNode struct {
	Address     string // FTN address (e.g. "21:1/100@fsxnet")
	Hostname    string // host:port
	SessionPwd  string // session password ("-" if none)
	NetworkName string // used for section comment markers
}

// BinkdConfig holds all data needed to generate or update binkd.conf.
type BinkdConfig struct {
	BBSRoot   string // absolute path to BBS root directory
	BoardName string // BBS name for sysname
	SysopName string // sysop name (falls back to "SysOp")
	Location  string // BBS location (falls back to "Earth")

	// Domains maps network name to zone (e.g. "fsxnet" -> 21).
	Domains map[string]int

	// Addresses lists all "address" lines (e.g. "21:4/158@fsxnet").
	Addresses []string

	// Node is the new hub node to add.
	Node BinkdNode
}

// sectionMarker returns the comment line used to identify a wizard-managed block.
func sectionMarker(networkName string) string {
	return fmt.Sprintf("# --- %s (added by FTN Setup Wizard) ---", networkName)
}

// isPlaceholderLine returns true if a line contains template placeholder data
// that should be replaced by the wizard.
func isPlaceholderLine(line string) bool {
	trimmed := strings.TrimSpace(line)

	// Skip comments and blank lines — they're not placeholders.
	if trimmed == "" || strings.HasPrefix(trimmed, "#") {
		return false
	}

	placeholders := []string{
		"hub.example.com",
		"/opt/vision3",
		"21:1/123@fsxnet",
		"3:1/456.1@fidonet",
		"\"My BBS\"",
		"\"Somewhere, USA\"",
		"\"SysOp\"",
		"PASSWORD",
	}
	for _, p := range placeholders {
		if strings.Contains(trimmed, p) {
			return true
		}
	}
	return false
}

// UpdateBinkdConf reads an existing binkd.conf, strips placeholder lines,
// injects real domain/address/node/sysname values from cfg, and writes
// the result back. Existing wizard-managed node blocks (from prior runs)
// are preserved. If the file doesn't exist, a fresh one is generated.
func UpdateBinkdConf(confPath string, cfg BinkdConfig) error {
	existing, err := os.ReadFile(confPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading binkd.conf: %w", err)
	}

	// Check if this node address already exists — skip if so.
	if len(existing) > 0 && nodeExists(string(existing), cfg.Node.Address) {
		return nil
	}

	outPath := filepath.Join(cfg.BBSRoot, "data", "ftn", "out")
	logPath := filepath.Join(cfg.BBSRoot, "data", "logs", "binkd.log")
	secureIn := filepath.Join(cfg.BBSRoot, "data", "ftn", "secure_in")
	insecureIn := filepath.Join(cfg.BBSRoot, "data", "ftn", "in")
	v3mailPath := filepath.Join(cfg.BBSRoot, "v3mail")

	sysop := cfg.SysopName
	if sysop == "" {
		sysop = "SysOp"
	}
	boardName := cfg.BoardName
	if boardName == "" {
		boardName = "Vision3 BBS"
	}
	location := cfg.Location
	if location == "" {
		location = "Earth"
	}

	var out strings.Builder

	if len(existing) == 0 {
		// Generate fresh binkd.conf.
		writeFreshBinkdConf(&out, cfg, outPath, logPath, secureIn, insecureIn, v3mailPath, boardName, sysop, location)
	} else {
		// Rewrite existing file: strip placeholders, inject real values.
		rewriteBinkdConf(&out, string(existing), cfg, outPath, logPath, secureIn, insecureIn, v3mailPath, boardName, sysop, location)
	}

	// Append the new node block.
	pwd := cfg.Node.SessionPwd
	if pwd == "" {
		pwd = "-"
	}
	fmt.Fprintf(&out, "\n%s\nnode %s %s %s\n",
		sectionMarker(cfg.Node.NetworkName),
		cfg.Node.Address,
		cfg.Node.Hostname,
		pwd)

	return writeFileAtomic(confPath, out.String(), 0600)
}

// nodeExists checks whether a node address is already defined in the config.
func nodeExists(content, address string) bool {
	scanner := bufio.NewScanner(strings.NewReader(content))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "node ") {
			fields := strings.Fields(line)
			if len(fields) >= 2 && fields[1] == address {
				return true
			}
		}
	}
	return false
}

// writeFreshBinkdConf generates a complete binkd.conf from scratch.
func writeFreshBinkdConf(out *strings.Builder, cfg BinkdConfig, outPath, logPath, secureIn, insecureIn, v3mailPath, boardName, sysop, location string) {
	out.WriteString("# binkd.conf - Generated by FTN Setup Wizard\n\n")

	// Domains.
	out.WriteString("#\n# Domains:\n#\n")
	for name, zone := range cfg.Domains {
		fmt.Fprintf(out, "domain %s %s %d\n", name, outPath, zone)
	}

	// Addresses.
	out.WriteString("\n#\n# Your Addresses:\n#\n")
	for _, addr := range cfg.Addresses {
		fmt.Fprintf(out, "address %s\n", addr)
	}

	// General settings.
	fmt.Fprintf(out, `
#
# General variables for your BBS:
#
sysname "%s"
location "%s"
sysop "%s"
nodeinfo 9600,TCP,BINKP
oblksize 4096
timeout 60
connect-timeout 0
call-delay 300
rescan-delay 60
maxservers 4
maxclients 1
log %s
loglevel 4
conlog 4
inbound %s
inbound-nonsecure %s
kill-dup-partial-files
kill-old-partial-files 86400
kill-old-bsy 43200
try 2
hold 1800
iport 24554
`, boardName, location, sysop, logPath, secureIn, insecureIn)

	// Exec / prescan.
	fmt.Fprintf(out, `
#
# Execute v3mail toss after receiving files:
#
prescan
exec "%s toss" *.[mwtfsMWTFS][oehrauOEHRAU][0-9a-zA-Z] *.pkt

#
# BinkD additional options:
#
percents
`, v3mailPath)
}

// rewriteBinkdConf filters an existing binkd.conf, replacing placeholder
// lines with real values and injecting missing domain/address lines.
func rewriteBinkdConf(out *strings.Builder, content string, cfg BinkdConfig, outPath, logPath, secureIn, insecureIn, v3mailPath, boardName, sysop, location string) {
	scanner := bufio.NewScanner(strings.NewReader(content))
	injectedDomains := false
	injectedAddresses := false

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Strip placeholder lines entirely.
		if isPlaceholderLine(line) {
			// If this is a domain placeholder, inject real domains once.
			if strings.HasPrefix(trimmed, "domain ") && !injectedDomains {
				for name, zone := range cfg.Domains {
					fmt.Fprintf(out, "domain %s %s %d\n", name, outPath, zone)
				}
				injectedDomains = true
			}
			// If this is an address placeholder, inject real addresses once.
			if strings.HasPrefix(trimmed, "address ") && !injectedAddresses {
				for _, addr := range cfg.Addresses {
					fmt.Fprintf(out, "address %s\n", addr)
				}
				injectedAddresses = true
			}
			// Replace sysname/sysop/log/inbound/exec placeholders.
			if strings.HasPrefix(trimmed, "sysname ") {
				fmt.Fprintf(out, "sysname \"%s\"\n", boardName)
				continue
			}
			if strings.HasPrefix(trimmed, "location ") {
				fmt.Fprintf(out, "location \"%s\"\n", location)
				continue
			}
			if strings.HasPrefix(trimmed, "sysop ") {
				fmt.Fprintf(out, "sysop \"%s\"\n", sysop)
				continue
			}
			if strings.HasPrefix(trimmed, "log ") {
				fmt.Fprintf(out, "log %s\n", logPath)
				continue
			}
			if strings.HasPrefix(trimmed, "inbound-nonsecure ") {
				fmt.Fprintf(out, "inbound-nonsecure %s\n", insecureIn)
				continue
			}
			if strings.HasPrefix(trimmed, "inbound ") {
				fmt.Fprintf(out, "inbound %s\n", secureIn)
				continue
			}
			if strings.HasPrefix(trimmed, "exec ") {
				fmt.Fprintf(out, "exec \"%s toss\" *.[mwtfsMWTFS][oehrauOEHRAU][0-9a-zA-Z] *.pkt\n", v3mailPath)
				continue
			}
			// Skip other placeholder lines (node hub.example.com, etc).
			continue
		}

		// Keep non-placeholder lines as-is.
		out.WriteString(line)
		out.WriteByte('\n')
	}

	// If we never hit a domain/address placeholder, inject at the end.
	if !injectedDomains {
		out.WriteString("\n#\n# Domains:\n#\n")
		for name, zone := range cfg.Domains {
			fmt.Fprintf(out, "domain %s %s %d\n", name, outPath, zone)
		}
	}
	if !injectedAddresses {
		out.WriteString("\n#\n# Your Addresses:\n#\n")
		for _, addr := range cfg.Addresses {
			fmt.Fprintf(out, "address %s\n", addr)
		}
	}
}

// BinkdIdentity holds BBS identity fields synced to binkd.conf.
type BinkdIdentity struct {
	BoardName string // sysname
	SysopName string // sysop
	Location  string // location
}

// SyncBinkdConf updates binkd.conf to reflect the current FTN link passwords
// and BBS identity fields (sysname, sysop, location). Only lines that differ
// from the current config are rewritten; if nothing changed the file is not
// touched. Called from saveAll so TUI edits are reflected automatically.
//
// links maps "address@network" (e.g. "21:1/100@fsxnet") to the session password.
func SyncBinkdConf(confPath string, identity BinkdIdentity, links map[string]string) error {
	existing, err := os.ReadFile(confPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // No binkd.conf to sync.
		}
		return fmt.Errorf("reading binkd.conf: %w", err)
	}

	var out strings.Builder
	changed := false
	scanner := bufio.NewScanner(strings.NewReader(string(existing)))

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// Sync sysname.
		if strings.HasPrefix(trimmed, "sysname ") && identity.BoardName != "" {
			newLine := fmt.Sprintf("sysname \"%s\"", identity.BoardName)
			if trimmed != newLine {
				out.WriteString(newLine)
				out.WriteByte('\n')
				changed = true
				continue
			}
		}

		// Sync sysop.
		if strings.HasPrefix(trimmed, "sysop ") && identity.SysopName != "" {
			newLine := fmt.Sprintf("sysop \"%s\"", identity.SysopName)
			if trimmed != newLine {
				out.WriteString(newLine)
				out.WriteByte('\n')
				changed = true
				continue
			}
		}

		// Sync location.
		if strings.HasPrefix(trimmed, "location ") && identity.Location != "" {
			newLine := fmt.Sprintf("location \"%s\"", identity.Location)
			if trimmed != newLine {
				out.WriteString(newLine)
				out.WriteByte('\n')
				changed = true
				continue
			}
		}

		// Sync node session passwords.
		if strings.HasPrefix(trimmed, "node ") {
			fields := strings.Fields(trimmed)
			if len(fields) >= 4 {
				addr := fields[1] // e.g. "21:1/100@fsxnet"
				if newPwd, ok := links[addr]; ok {
					if newPwd == "" {
						newPwd = "-"
					}
					if fields[3] != newPwd {
						fields[3] = newPwd
						out.WriteString(strings.Join(fields, " "))
						out.WriteByte('\n')
						changed = true
						continue
					}
				}
			}
		}

		out.WriteString(line)
		out.WriteByte('\n')
	}

	if !changed {
		return nil
	}
	return writeFileAtomic(confPath, out.String(), 0600)
}

// writeFileAtomic creates the parent directory if needed and writes content via
// a temp file + rename, so callers never see a partial/empty binkd.conf and
// fresh installs (where data/ftn doesn't exist yet) don't fail.
func writeFileAtomic(path, content string, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating dir for %s: %w", path, err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp.*")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpName := tmp.Name()
	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()        // cleanup on error path
		_ = os.Remove(tmpName) // cleanup on error path
		return fmt.Errorf("writing %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpName) // cleanup on error path
		return fmt.Errorf("closing %s: %w", path, err)
	}
	if err := os.Chmod(tmpName, perm); err != nil {
		_ = os.Remove(tmpName) // cleanup on error path
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		_ = os.Remove(tmpName) // cleanup on error path
		return fmt.Errorf("installing %s: %w", path, err)
	}
	return nil
}
