#!/bin/bash

# --------------------------------------------------------
# Launch a local dosemu2 session for configuring DOS doors.
#
# This starts dosemu2 without COM1 serial redirection,
# giving you a direct DOS command prompt to install and
# configure door programs on the virtual C: drive.
#
# Usage: ./scripts/dos-local.sh [drive_c_path]
#
#   drive_c_path  Optional path to drive_c directory.
#                 Defaults to doors/drive_c/ relative to BBS root.
#                 BBS root is auto-detected from the script's
#                 location in the repository.
# --------------------------------------------------------

trap '' 2

stty cols 80 rows 25

# Resolve BBS root from script location: scripts/ -> repo root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BBS_ROOT="$(dirname "$SCRIPT_DIR")"

DRIVE_C="${1:-$BBS_ROOT/doors/drive_c}"
LOG_DIR="$DRIVE_C/nodes"
DOSEMU_BIN="/usr/libexec/dosemu2/dosemu2.bin"

if [ ! -d "$DRIVE_C" ]; then
    echo "Error: drive_c directory not found: $DRIVE_C"
    exit 1
fi

if [ ! -x "$DOSEMU_BIN" ]; then
    echo "Error: dosemu2.bin not found at $DOSEMU_BIN"
    exit 1
fi

mkdir -p "$LOG_DIR"

# Generate a temporary dosemurc from the user's base config,
# stripping $_com1 (no serial port needed for local sessions)
# and $_hdimage/$_video (managed via CLI args).
TMPRC="$(mktemp)"
trap 'rm -f "$TMPRC"; trap - 2' EXIT

BASE_RC="$HOME/.dosemu/.dosemurc"
if [ -f "$BASE_RC" ]; then
    grep -v '^\s*\$_com1\|^\s*\$_hdimage\|^\s*\$_video\|^\s*\$_vga' "$BASE_RC" > "$TMPRC"
else
    cat > "$TMPRC" << 'RCEOF'
$_cpu = "80486"
$_cpu_vm = "auto"
$_xms = (1024)
$_ems = (1024)
$_ems_frame = (0xe000)
$_external_char_set = "cp437"
$_internal_char_set = "cp437"
$_term_updfreq = (8)
$_layout = "us"
$_rawkeyboard = (auto)
$_speaker = ""
$_sound = (off)
RCEOF
fi

# Append terminal mode settings
cat >> "$TMPRC" << RCEOF

# Generated by dos-local.sh
\$_lredir_paths = "$DRIVE_C"
\$_term_color = (on)
\$_term_esc_char = (27)
RCEOF

"$DOSEMU_BIN" \
    -t \
    -f "$TMPRC" \
    --Fdrive_c "$DRIVE_C" \
    -o "$LOG_DIR/dosemu_local.log"

trap - 2
